site_name: James Philbrick

nav:
  - Home: 'index.md'
  - Contact: 'contact.md'

theme:
  name: material
  palette:
    scheme: modern-terracotta
  font:
    text: Lato
    heading: Bree Serif
  logo: assets/icons/vector-fowl-background.svg
  favicon: assets/icons/favicon.png

extra_css:
  - stylesheets/extra.css

plugins:
  - offline
  - search
  - blog:
      authors_file: "{blog}/.authors.yml"

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2024 James Philbrick.

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<james.philbrick@gmail.com>